M48
; DRILL file {KiCad 9.0.8+dfsg-1} date 2026-07-03T16:45:12-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-03T16:45:12-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X159.413Y-84.88
X159.413Y-112.82
X183.543Y-69.64
X189.893Y-117.9
M30
